# Generated by Django 4.1.1 on 2022-09-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('task', models.TextField(verbose_name='Task')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Create on')),
                ('author', models.CharField(max_length=40, verbose_name='Author')),
            ],
        ),
    ]
